import { defineConfig, defineDocs, frontmatterSchema, metaSchema } from "fumadocs-mdx/config";
import { z } from "zod";
import { remarkMermaid } from "./lib/remark-mermaid.mjs";

/**
 * content/docs/ is generated by scripts/sync-docs.mjs from the template repo at the ref pinned in
 * docs.source.json, and is gitignored. Pages are plain Markdown (.md), so the source text needs no escaping.
 */
export const docs = defineDocs({
  dir: "content/docs",
  docs: {
    schema: frontmatterSchema.extend({
      /** The source's own title (H1 or README section heading); `title` may be a shorter sidebar label. */
      heading: z.string(),
      /** Repo path the page was cut from, and its GitHub URL at the pinned ref. */
      sourcePath: z.string(),
      sourceUrl: z.string(),
    }),
  },
  meta: { schema: metaSchema },
});

export default defineConfig({
  mdxOptions: {
    remarkPlugins: [remarkMermaid],
    rehypeCodeOptions: {
      themes: { light: "github-light", dark: "github-dark" },
    },
  },
});
