import { defineConfig, defineDocs, frontmatterSchema, metaSchema } from "fumadocs-mdx/config";
import { z } from "zod";
import { rehypeCodeDefaultOptions } from "fumadocs-core/mdx-plugins";
import type { ShikiTransformer } from "shiki";
import { remarkMermaid } from "./lib/remark-mermaid.mjs";

/**
 * content/docs/ is generated by scripts/sync-docs.mjs from the template repo at the ref pinned in
 * docs.source.json, and is gitignored. Pages are plain Markdown (.md), so the source text needs no escaping.
 */
export const docs = defineDocs({
  dir: "content/docs",
  docs: {
    schema: frontmatterSchema.extend({
      /** The source's own title (H1 or README section heading); `title` may be a shorter sidebar label. */
      heading: z.string(),
      /** Repo path the page was cut from, and its GitHub URL at the pinned ref. */
      sourcePath: z.string(),
      sourceUrl: z.string(),
    }),
  },
  meta: { schema: metaSchema },
});

/** GitHub's themes draw comments at 3.6:1 on our code background; lift them to WCAG AA (4.5:1) in both modes. */
const readableComments: ShikiTransformer = {
  name: "readable-comments",
  span(node) {
    const style = node.properties.style;
    if (typeof style === "string")
      node.properties.style = style.replace(/--shiki-light:#6a737d/i, "--shiki-light:#57606a").replace(/--shiki-dark:#6a737d/i, "--shiki-dark:#959da5");
  },
};

export default defineConfig({
  mdxOptions: {
    remarkPlugins: [remarkMermaid],
    rehypeCodeOptions: {
      themes: { light: "github-light", dark: "github-dark" },
      transformers: [...(rehypeCodeDefaultOptions.transformers ?? []), readableComments],
    },
  },
});
